// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\bjain\serviceNest\interfaces\householder_repository_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	model "serviceNest/model"

	gomock "github.com/golang/mock/gomock"
)

// MockHouseholderRepository is a mock of HouseholderRepository interface.
type MockHouseholderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHouseholderRepositoryMockRecorder
}

// MockHouseholderRepositoryMockRecorder is the mock recorder for MockHouseholderRepository.
type MockHouseholderRepositoryMockRecorder struct {
	mock *MockHouseholderRepository
}

// NewMockHouseholderRepository creates a new mock instance.
func NewMockHouseholderRepository(ctrl *gomock.Controller) *MockHouseholderRepository {
	mock := &MockHouseholderRepository{ctrl: ctrl}
	mock.recorder = &MockHouseholderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHouseholderRepository) EXPECT() *MockHouseholderRepositoryMockRecorder {
	return m.recorder
}

// GetHouseholderByID mocks base method.
func (m *MockHouseholderRepository) GetHouseholderByID(id string) (*model.Householder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHouseholderByID", id)
	ret0, _ := ret[0].(*model.Householder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHouseholderByID indicates an expected call of GetHouseholderByID.
func (mr *MockHouseholderRepositoryMockRecorder) GetHouseholderByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHouseholderByID", reflect.TypeOf((*MockHouseholderRepository)(nil).GetHouseholderByID), id)
}

// SaveHouseholder mocks base method.
func (m *MockHouseholderRepository) SaveHouseholder(householder *model.Householder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHouseholder", householder)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveHouseholder indicates an expected call of SaveHouseholder.
func (mr *MockHouseholderRepositoryMockRecorder) SaveHouseholder(householder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHouseholder", reflect.TypeOf((*MockHouseholderRepository)(nil).SaveHouseholder), householder)
}
