package errs

const UserNotFound = "user not found"
const EmailAlreadyUse = "email already in use"
const ServiceRequestNotFound = "service request not found"
const ErrorParsingRequestTime = "error parsing requested_time"
const ErrorParsingScheduleTime = "error parsing scheduled_time"
const NoServiceProviderFoundForRequestId = "no service provider found for request id"
const ServiceNotFound = "service not found"
const ServiceIdNotExists = "service id not exists"
const InvalidServiceId = "invalid service id"
const ProviderNotFound = "provider not found"
const ProviderNotExists = "provider not exists"
const FailCalculateRating = "fail to calculate rating"
const FailUpdateRating = "fail to update rating"
const RequestNotBelongToHouseholder = "service request does not belong to the householder"
const OnlyAcceptedRequestCancelled = "only accepted service requests can be canceled"
const RequestAlreadyCancelled = "request is already cancelled"
const OnlyPendingRequestRescheduled = "only pending request rescheduled"
const RequestAlreadyApproved = "request is already approved"
const NotUpdateProviderDetails = "not update provider details"
const NotUpdateRequest = "not update request"
const NotRetrieveRequest = "not retrieve request"
const NoApproveRequestFound = "no approve request found"
const IncorrectSecurityAnswer = "incorrect security answer"
const RequestCancellationTooLate = "cancellation not allowed within 4 hours of the scheduled time"
